[package]
name = "ddai_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
dotenvy = "0.15"
ddai_store = { path = "../ddai_store" }
ddai_ingest = { path = "../ddai_ingest" }